### ISSUE TITLE
Containerd `MaxContainerLogLineSize` misconfig

### ISSUE THREAD

**Issue by lingdie** [labring-actions/runtime#14]
https://github.com/labring-actions/runtime/blob/443cc6f4625a6a505586dba5e90a71adec275639/containerd/etc/config.toml.tmpl#L28

Should set to a positive int.

**Comment by muicoder** [comment]
https://github.com/containerd/containerd/blob/release/1.7/docs/cri/config.md?plain=1#L172

**Comment by lingdie** [comment]
https://github.com/labring-actions/runtime/pull/15

**Comment by lingdie** [comment]
you can use codes below for test.

```go
package main

import (
	"bytes"
	"flag"
	"fmt"
	"time"
)

var outputBytes int

func main() {
	flag.IntVar(&outputBytes, "n", 1000, "number of bytes to output")
	flag.Parse()
	output := bytes.Buffer{}
	for i := 0; i < outputBytes; i++ {
		output.Write([]byte{'a'})
	}
	for {
		fmt.Printf("%v", output)
		time.Sleep(1 * time.Second)
	}
}

```
